FROM ##base_image
MAINTAINER alexsl

ARG DOCKER_GROUP
ARG USERID
ARG GROUPID

RUN sudo echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" \
    | sudo tee /etc/apt/sources.list.d/webupd8team-java.list && \
    sudo echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" \
    | sudo tee -a /etc/apt/sources.list.d/webupd8team-java.list && \
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 && \
    sudo apt-get update && \
    sudo echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true \ 
    | sudo /usr/bin/debconf-set-selections && \
    sudo apt-get install -y oracle-java8-installer libxext-dev libxrender-dev libxtst-dev && \
    sudo apt-get clean -y && \
    sudo rm -rf /var/lib/apt/lists/* && \
    sudo rm -rf /tmp/*
