FROM ##base_image
MAINTAINER alexsl

ARG DOCKER_GROUP
ARG USERID
ARG GROUPID

RUN sudo echo "deb http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic main" \
    | sudo tee /etc/apt/sources.list.d/linuxuprising-java.list && \
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 73C3DB2A && \
    sudo apt-get update && \
    sudo echo oracle-java11-installer shared/accepted-oracle-license-v1-2 select true \
    | sudo /usr/bin/debconf-set-selections && \
    sudo apt-get install -y oracle-java11-installer libxext-dev libxrender-dev libxtst-dev && \
    sudo apt-get clean -y && \
    sudo rm -rf /var/lib/apt/lists/* && \
    sudo rm -rf /tmp/*
