FROM ##base_image
MAINTAINER alexsl

RUN sudo apt-get update && \
    sudo apt-get install -y curl && \
    curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | sudo bash && \
    sudo apt-get update && \
    sudo apt-get install -y gitlab-ci-multi-runner && \
    sudo apt-get clean -y && \
    sudo rm -rf /var/lib/apt/lists/* && \
    sudo rm -rf /tmp/*
