FROM ##base_image
MAINTAINER rzhurak@larch-networks.com

ARG DOCKER_GROUP
ARG USERID
ARG GROUPID

RUN sudo apt-get update  \
    && sudo apt-get install -y screen build-essential chrpath device-tree-compiler diffstat gawk cpio texinfo && \
    sudo apt-get clean -y && \
    sudo rm -rf /var/lib/apt/lists/* && \
    sudo rm -rf /tmp/*
