FROM debian:jessie
MAINTAINER rzhurak@larch-networks.com

ARG USER=developer
ARG DOCKER_GROUP=999
ARG USERID=1000
ARG GROUPID=1000
ARG HOME=/home/${USER}

# Adding ${USER} to the container system
COPY /.bashrc ${HOME}/
COPY /.gitconfig ${HOME}/
RUN groupadd -g ${DOCKER_GROUP} docker \
    && mkdir -p ${HOME} \
    && echo "${USER}:x:${USERID}:${GROUPID}:${USER},,,:${HOME}:/bin/bash" >> /etc/passwd \
    && echo "${USER}:x:${GROUPID}:" >> /etc/group \
    && mkdir -p /etc/sudoers.d/ \
    && echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER} \
    && chown ${USER}:${USER} -R ${HOME} \
    && chmod 0440 /etc/sudoers.d/${USER} \
    && usermod -aG docker ${USER}

# Installing generic packages 
RUN echo "deb http://ftp.ua.debian.org/debian jessie main" > /etc/apt/sources.list \
    && echo "deb http://security.debian.org/debian-security jessie/updates main" >> /etc/apt/sources.list \
    && apt-get update && apt upgrade -y \
    && apt-get install -y software-properties-common \
    && apt-get install -y sudo ssh git vim mc tmux curl bash-completion tcl-dev gettext xz-utils \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*

RUN GIT_VER=git-2.22.0; cd /tmp \
    && curl -L https://www.kernel.org/pub/software/scm/git/${GIT_VER}.tar.xz -o ${GIT_VER}.tar.xz \
    && tar -xaf ${GIT_VER}.tar.xz && cd ${GIT_VER} \
    && ./configure --prefix=/usr && make && sudo make install \
    && cd - && rm -rf /tmp/*

USER developer

ENV USER=${USER}
#XXX is HOME env variable really required?
ENV HOME=${HOME}

WORKDIR ${HOME}
