FROM ubuntu:xenial
MAINTAINER alexsl

ARG DOCKER_GROUP
ARG USERID
ARG GROUPID

RUN groupadd -g ${DOCKER_GROUP} docker && \
    mkdir -p /home/developer && \
    echo "developer:x:${USERID}:${GROUPID}:developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${GROUPID}:" >> /etc/group && \
    mkdir -p /etc/sudoers.d/ && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chown developer:developer -R /home/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    usermod -aG docker developer && \
    sed -i 's/archive.ubuntu.com/ua.archive.ubuntu.com/' /etc/apt/sources.list && \
    apt-get update && apt-get install -y software-properties-common && \
    apt-get install -y sudo \
    ssh git mercurial subversion vim mc tmux && \
    apt-get -y clean && \
    chown developer:developer -R /home/developer && \
    usermod -aG docker developer && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

USER developer
ENV HOME /home/developer
WORKDIR /home/developer
