FROM ##base_image
MAINTAINER alexsl

ARG DOCKER_GROUP
ARG USERID
ARG GROUPID

ENV DISPLAY=${DISPLAY}

RUN wget -nv -O - http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/technology/epp/downloads/release/2019-06/R/eclipse-cpp-2019-06-R-linux-gtk-x86_64.tar.gz | tar xz

CMD [ "/home/developer/eclipse/eclipse"]
